name: Docker Image Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build -t maartje/tls-ping-ping:$GITHUB_SHA ./
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}"
      - name: Push image
        run: docker push maartje/tls-ping-ping:$GITHUB_SHA